# Generated by Django 6.1.2 on 2026-10-06 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_siniestro', models.UUIDField(blank=True, null=True)),
                ('id_poliza', models.UUIDField(blank=True, null=True)),
                ('document_type', models.CharField(max_length=50)),
                ('file_url', models.TextField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('contenido', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento',
                'indexes': [models.Index(fields=['id_siniestro'], name='idx_documento_siniestro'), models.Index(fields=['id_poliza'], name='idx_documento_poliza')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id_log', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('lectura', 'Lectura'), ('descarga', 'Descarga'), ('modificacion', 'Modificación'), ('carga', 'Carga')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='documentos.documento')),
            ],
            options={
                'db_table': 'document_access_log',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['documento'], name='idx_document_access_log_doc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['lectura', 'descarga', 'modificacion', 'carga'])), name='chk_access_log_action')],
            },
        ),
    ]
